name: IceCat
version: '2.2.0'
main: jp.iceserver.icecat.IceCat
api-version: 1.18
authors: [ Minidon, Zaemon ]
description: アイス生活鯖のインフラ周りを補うためのプラグイン
website: https://github.com/IceServerLab/IceCat
depend:
  - LuckPerms

commands:
  coi:
    description: /co i を省略したコマンド
  nickname:
    description: ニックネームの変更をするためのコマンド
    permission: icecat.command.nickname
    permission-message: "§cあなたに実行する権限がありません。"
  report:
    description: レポートをするためのコマンド
  gamemode:
    description: ゲームモードを変更するためのコマンド
    permission: icecat.command.gamemode
  home:
    description: ホームにテレポートするためのコマンド
    permission: icecat.command.home
  sethome:
    description: ホームを現在地に設定するためのコマンド
    permission: icecat.command.sethome
  death:
    description: 死んだポイントまで1度だけテレポートできるコマンド
    permission: icecat.command.death
  afk:
    description: Afkを切り替えるためのコマンド
    permission: icecat.command.afk
  staff:
    description: スタッフと一般を切り替えるためのコマンド
    permission: icecat.command.staff

permissions:
  #  global
  icecat.*:
    description: 全権限
    default: op
    children:
      icecat.command.*: true

  #  allCommand
  icecat.command.*:
    description: コマンドの全権限
    children:
      icecat.command.nickname: true
      icecat.command.gamemode.*: true

  #  nickname
  icecat.command.nickname:
    description: ニックネームの変更をするための権限
    default: op

  #  gamemode
  icecat.command.gamemode:
    description: ゲームモードコマンド
  icecat.command.gamemode.*:
    description: 全てのゲームモードへ変更するための権限
    default: op
    children:
      icecat.command.gamemode.survival: true
      icecat.command.gamemode.creative: true
      icecat.command.gamemode.adventure: true
      icecat.command.gamemode.spectator: true
  icecat.command.gamemode.survival:
    description: サバイバルモードへ変更するための権限
    children:
      icecat.command.gamemode: true
  icecat.command.gamemode.creative:
    description: クリエイティブモードへ変更するための権限
    children:
      icecat.command.gamemode: true
  icecat.command.gamemode.adventure:
    description: アドベンチャーモードへ変更するための権限
    children:
      icecat.command.gamemode: true
  icecat.command.gamemode.spectator:
    description: スペクテイターモードへ変更するための権限
    children:
      icecat.command.gamemode: true
  icecat.command.gamemode.other.*:
    description: 他のプレイヤーのゲームモードを変更するための権限
    children:
      icecat.command.gamemode: true
      icecat.command.gamemode.other.survival: true
      icecat.command.gamemode.other.creative: true
      icecat.command.gamemode.other.adventure: true
      icecat.command.gamemode.other.spectator: true
  icecat.command.gamemode.other.survival:
    description: サバイバルモードへ変更するための権限
  icecat.command.gamemode.other.creative:
    description: クリエイティブモードへ変更するための権限
  icecat.command.gamemode.other.adventure:
    description: アドベンチャーモードへ変更するための権限
  icecat.command.gamemode.other.spectator:
    description: スペクテイターモードへ変更するための権限

  # home
  icecat.command.home:
    description: ホームにてレポートするための権限
    default: true
    children:
      icecat.command.sethome: true
  icecat.command.sethome:
    description: ホームを現在地に設定するための権限
    default: true

  # death
  icecat.command.death:
    description: 死亡ポイントにてレポートするための権限
    default: true

  # afk
  icecat.command.afk:
    description: 自身のAfkを切り替えるための権限
    default: true
  icecat.command.afk.other:
    description: 他人のAfkを切り替えるための権限
    default: op

  # staff
  icecat.command.staff:
    description: 自身のスタッフと一般を切り替えるための権限
    default: op
  icecat.command.staff.other:
    description: 他人のスタッフと一般を切り替えるための権限
    default: op